lint

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -28,6 +28,10 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
+      - name: Lint
+        run: npm run lint || echo "Lint failed"
+        continue-on-error: true
+
       - name: Build Vite project
         run: npm run build
 
